# Generated by Django 4.2.3 on 2023-08-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_rename_advertisement_advertisements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisement',
        ),
    ]
